name: project1

services:

  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # postgres_data is just volume name
      # in real, pg stores data here /var/lib/postgresql/data
    ports:
      - "5432:5432"
    # health check is not one time setup, runs in bg
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"] # use container cmd
      # pg_isready is pg tool to check server status
      interval: 10s # check every
      timeout: 5s  # time to respond for server
      retries: 5  # if not respond, retires
      start_period: 5s # this check starts after 10s

  redis:
    # if url not given, consider it default
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    # command tells to run this only
    # not default boot up which saves redis data to disk temporaly
    # lost if volume not set
    # > is just so that we can write commands in multiple lines
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  qdrant:
    image: qdrant/qdrant:v1.9.7 
    # latest version images are breaking for payload filters
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333" 
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:6333/readyz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

    

  migrate:
  # if i placed this inside api service as a command,
  # in scaling, all replica containers of api will try to run it at same time. 
    build:
      # either build or look for image to pull
      # if build, then first check cache if already build in another service
      # we must give build here, bz each service is though isolated.
      context: . # looks inside this folder for files, and dockerfile
      target: runner # build till this stage, including runner
    container_name: migrate
    restart: "no" # only run this once, then turn off
    env_file: # all those services which req settings() to init, must give all env
      - .env
    command: ["alembic", "upgrade", "head"]
    depends_on:
      postgres:
        condition: service_healthy
    
  minio:
    image: minio/minio:latest
    container_name: local_minio
    ports:
      - "9000:9000" # s3 storage server with full aws like apis
      - "9001:9001" # admin only ui
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}      
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}  
      MINIO_NOTIFY_WEBHOOK_ENABLE_FASTAPI: ${MINIO_NOTIFY_WEBHOOK_ENABLE_FASTAPI}
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_FASTAPI: ${MINIO_NOTIFY_WEBHOOK_ENDPOINT_FASTAPI}

    volumes:
      - minio_data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
      # if docker container wants to send to local pc url
    command: server /data --console-address ":9001"
    # this is imp to tell its role as server else crash

  api:
    build:
      context: .
      target: runner
    container_name: api
    restart: unless-stopped
    env_file:
      - .env
    # environment:
    #   DD_AGENT_HOST: datadog
    #   DD_TRACE_AGENT_PORT: "8126"
    #   DD_SERVICE: clause-api
    #   DD_ENV: ${DD_ENV:-development}
    #   DD_VERSION: ${DD_VERSION:-0.1.0}
    #   DD_LOGS_INJECTION: "true"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      qdrant:
        condition: service_healthy

    healthcheck:
      disable: true
    # labels:
    #   com.datadoghq.ad.logs: '[{"source": "python", "service": "clause-api"}]'


  
  # datadog:
  #   image: gcr.io/datadoghq/agent:7
  #   container_name: clause_datadog
  #   restart: unless-stopped
  #   environment:
  #     DD_API_KEY: ${DD_API_KEY}
  #     DD_SITE: datadoghq.com
  #     DD_ENV: ${DD_ENV:-development}
  #     DD_APM_ENABLED: "true"
  #     DD_APM_NON_LOCAL_TRAFFIC: "true"          # accept traces from app container
  #     DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"    # accept metrics from app container
  #     DD_PROCESS_AGENT_ENABLED: "true"
  #     DD_CONTAINER_LABELS_AS_TAGS: "true"
  #     DD_LOGS_ENABLED: "true"
  #     DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - /proc/:/host/proc/:ro
  #     - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
  #     - /var/lib/docker/containers:/var/lib/docker/containers:ro
  #   ports:
  #     - "8126:8126"   # APM trace receiver
  #     - "8125:8125/udp" # DogStatsD metrics


volumes:
  postgres_data:
  redis_data:
  minio_data:
  qdrant_data:
