name: project1

services:

  redis:
    # if url not given, consider it default
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    # command tells to run this only
    # not default boot up which saves redis data to disk temporaly
    # lost if volume not set
    # > is just so that we can write commands in multiple lines
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  api:
    build:
    # either build or look for image to pull
    # if build, then first check cache if already build in another service
      context: .
      target: runner
    container_name: api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      qdrant:
        condition: service_healthy

    healthcheck:
      disable: true

volumes:
  postgres_data:
  redis_data:
  minio_data:
  qdrant_data:

